# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
  amadeus_key: ZRjgUbT6jlJZlEvY86DrhyOrXAGzvANA
#    parameter_name: value

services:

    attraction.search_filter:
        parent:    "api_platform.doctrine.orm.search_filter"
        arguments: [ { addressLocality: "partial", geo.latitude: "partial", geo.longitude: "partial"  } ]
        tags:      [ { name: 'api_platform.filter', id: 'attraction.search' } ]

    touristAttraction.collection_data_provider:
        class: 'AppBundle\DataProvider\TouristAttractionCollectionDataProvider'
        arguments: ["@request_stack","@doctrine", "%amadeus_key%"]
        tags:
            -  { name: 'api_platform.collection_data_provider', priority: 2 }


